// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviesAPI.Persistence.DbContexts;

#nullable disable

namespace MoviesAPI.Migrations.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20231204045504_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MoviesAPI.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdateDate")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1830f0c5-ce23-45e1-8aae-b345344f86f5"),
                            InsertDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Action & Adventure"
                        },
                        new
                        {
                            Id = new Guid("27e7f102-e460-4095-87ba-67e1b2cc5932"),
                            InsertDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Drama"
                        },
                        new
                        {
                            Id = new Guid("3de1f5c8-ffca-4ee6-92e8-0c9eb9074959"),
                            InsertDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sci-Fi & Fantasy"
                        },
                        new
                        {
                            Id = new Guid("41473391-23d1-496d-8cc3-0ea3003fd5db"),
                            InsertDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "History"
                        },
                        new
                        {
                            Id = new Guid("429f6d4e-885b-4607-897a-f3ecbfa7b9e6"),
                            InsertDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Horror"
                        },
                        new
                        {
                            Id = new Guid("432d1f42-3d1c-44b7-a40c-9b96d3a07aeb"),
                            InsertDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mistery"
                        },
                        new
                        {
                            Id = new Guid("6f7daea1-c1e7-4ce6-b0d2-eef87b11fc6d"),
                            InsertDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = new Guid("7a9bdf52-bd33-4092-8669-9ded0ef5b704"),
                            InsertDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Action"
                        });
                });

            modelBuilder.Entity("MoviesAPI.Models.Models.MovieCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdateDate")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = new Guid("1830f0c5-ce23-45e1-8aae-b345344f86f5"),
                            InsertDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = new Guid("278490e6-da09-4d49-84a9-cc0f0f4fc6b2")
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = new Guid("27e7f102-e460-4095-87ba-67e1b2cc5932"),
                            InsertDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = new Guid("278490e6-da09-4d49-84a9-cc0f0f4fc6b2")
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = new Guid("3de1f5c8-ffca-4ee6-92e8-0c9eb9074959"),
                            InsertDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = new Guid("278490e6-da09-4d49-84a9-cc0f0f4fc6b2")
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = new Guid("27e7f102-e460-4095-87ba-67e1b2cc5932"),
                            InsertDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = new Guid("2be04001-c8aa-4f06-a21a-e135c637db35")
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = new Guid("41473391-23d1-496d-8cc3-0ea3003fd5db"),
                            InsertDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = new Guid("2be04001-c8aa-4f06-a21a-e135c637db35")
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = new Guid("429f6d4e-885b-4607-897a-f3ecbfa7b9e6"),
                            InsertDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = new Guid("3869f5ef-43a3-44dd-b6fa-fff4057173e9")
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = new Guid("432d1f42-3d1c-44b7-a40c-9b96d3a07aeb"),
                            InsertDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = new Guid("3869f5ef-43a3-44dd-b6fa-fff4057173e9")
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = new Guid("27e7f102-e460-4095-87ba-67e1b2cc5932"),
                            InsertDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = new Guid("4db341fb-2490-46c3-bf8f-bc4900ca2f49")
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = new Guid("3de1f5c8-ffca-4ee6-92e8-0c9eb9074959"),
                            InsertDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = new Guid("4db341fb-2490-46c3-bf8f-bc4900ca2f49")
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = new Guid("6f7daea1-c1e7-4ce6-b0d2-eef87b11fc6d"),
                            InsertDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = new Guid("6e54c2e8-f5ab-4fb2-8459-5ce4c728ca08")
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = new Guid("7a9bdf52-bd33-4092-8669-9ded0ef5b704"),
                            InsertDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = new Guid("6e54c2e8-f5ab-4fb2-8459-5ce4c728ca08")
                        });
                });

            modelBuilder.Entity("MoviesAPI.Models.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Picture")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdateDate")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("278490e6-da09-4d49-84a9-cc0f0f4fc6b2"),
                            Description = "The Doctor is a Time Lord: a 900 year old alien with 2 hearts, part of a gifted civilization who mastered time travel. The Doctor saves planets for a living—more of a hobby actually, and the Doctor's very, very good at it.",
                            InsertDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Doctor Who",
                            Picture = "https://www.themoviedb.org/t/p/w300_and_h450_bestv2/4edFyasCrkH4MKs6H4mHqlrxA6b.jpg",
                            Title = "Doctor Who",
                            Year = 2005
                        },
                        new
                        {
                            Id = new Guid("2be04001-c8aa-4f06-a21a-e135c637db35"),
                            Description = "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
                            InsertDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Oppenheimer",
                            Picture = "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
                            Title = "Oppenheimer",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("3869f5ef-43a3-44dd-b6fa-fff4057173e9"),
                            Description = "Recently fired and desperate for work, a troubled young man named Mike agrees to take a position as a night security guard at an abandoned theme restaurant: Freddy Fazbear's Pizzeria. But he soon discovers that nothing at Freddy's is what it seems.",
                            InsertDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Five Nights at Freddy's",
                            Picture = "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/j9mH1pr3IahtraTWxVEMANmPSGR.jpg",
                            Title = "Five Nights at Freddy's",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("4db341fb-2490-46c3-bf8f-bc4900ca2f49"),
                            Description = "After stealing the Tesseract during the events of “Avengers: Endgame,” an alternate version of Loki is brought to the mysterious Time Variance Authority, a bureaucratic organization that exists outside of time and space and monitors the timeline. They give Loki a choice: face being erased from existence due to being a “time variant” or help fix the timeline and stop a greater threat.",
                            InsertDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Loki",
                            Picture = "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/voHUmluYmKyleFkTu3lOXQG702u.jpg",
                            Title = "Loki",
                            Year = 2021
                        },
                        new
                        {
                            Id = new Guid("6e54c2e8-f5ab-4fb2-8459-5ce4c728ca08"),
                            Description = "\r\n\r\nFinding himself in a new era, and approaching retirement, Indy wrestles with fitting into a world that seems to have outgrown him. But as the tentacles of an all-too-familiar evil return in the form of an old rival, Indy must don his hat and pick up his whip once more to make sure an ancient and powerful artifact doesn't fall into the wrong hands.\r\n",
                            InsertDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Indiana Jones and the Dial of Destiny",
                            Picture = "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/Af4bXE63pVsb2FtbW8uYIyPBadD.jpg",
                            Title = "Indiana Jones and the Dial of Destiny",
                            Year = 2023
                        });
                });

            modelBuilder.Entity("MoviesAPI.Models.Models.MovieCategory", b =>
                {
                    b.HasOne("MoviesAPI.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoviesAPI.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Movie");
                });
#pragma warning restore 612, 618
        }
    }
}
